/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'activity',
    path: '/activity',
    component: 'layout.base$view.activity',
    meta: {
      title: '活动管理',
      icon: 'mdi:calendar-star',
      order: 7,
      i18nKey: 'route.activity'
    }
  },
  {
    name: 'adoption',
    path: '/adoption',
    component: 'layout.base$view.adoption',
    meta: {
      title: '领养审核',
      icon: 'mdi:heart-outline',
      order: 4,
      i18nKey: 'route.adoption'
    }
  },
  {
    name: 'comment',
    path: '/comment',
    component: 'layout.base$view.comment',
    meta: {
      title: '评论管理',
      icon: 'mdi:comment-text-outline',
      order: 9,
      i18nKey: 'route.comment'
    }
  },
  {
    name: 'dict',
    path: '/dict',
    component: 'layout.base$view.dict',
    meta: {
      title: '数据字典',
      icon: 'mdi:book-settings',
      order: 10,
      i18nKey: 'route.dict'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: '首页看板',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'pet',
    path: '/pet',
    component: 'layout.base$view.pet',
    meta: {
      title: '宠物管理',
      icon: 'mdi:paw',
      order: 2,
      i18nKey: 'route.pet'
    }
  },
  {
    name: 'rescue',
    path: '/rescue',
    component: 'layout.base$view.rescue',
    meta: {
      title: '救助记录',
      icon: 'mdi:ambulance',
      order: 3,
      i18nKey: 'route.rescue'
    }
  },
  {
    name: 'station',
    path: '/station',
    component: 'layout.base$view.station',
    meta: {
      title: '救助站管理',
      icon: 'mdi:hospital-building',
      order: 5,
      i18nKey: 'route.station'
    }
  },
  {
    name: 'supply',
    path: '/supply',
    component: 'layout.base$view.supply',
    meta: {
      title: '物资管理',
      icon: 'mdi:package-variant',
      order: 6,
      i18nKey: 'route.supply'
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base$view.user',
    meta: {
      title: '用户管理',
      icon: 'mdi:account-group',
      order: 8,
      i18nKey: 'route.user'
    }
  }
];
